# -*- coding: utf-8 -*-
"""problem-07-01111092.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cVjm6amTY_EllMbNYEuN4Zrb8maSIol
"""

print("Enter the first list : ")
f_list=list(map(int,input().split()))
print("First list : ",f_list)

print("Enter the second list : ")
s_list=list(map(int,input().split()))
print("Second list : ",s_list)

print("Element at odd-index positions from list one:",list(item for item in f_list if f_list.index(item)%2!=0))
print("Element at odd-index positions from list one:",list(item for item in s_list if s_list.index(item)%2==0))

l_list=list(item for item in f_list if f_list.index(item)%2!=0)
l_list.extend(list(item for item in s_list if s_list.index(item)%2==0))
print("Printing Final third list :",l_list)