# -*- coding: utf-8 -*-
"""problem-02-01111092.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cVjm6amTY_EllMbNYEuN4Zrb8maSIol
"""

str=input("Enter the input string : ")
flag=None
for i in range(int(len(str)/2)):
  if str[i]!=str[len(str)-i-1]:
    flag=1
if flag==None:
  print(str+" is a palindrome")
else:
  print(str+" is not a palindrome")