# -*- coding: utf-8 -*-
"""problem-04-01111092.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cVjm6amTY_EllMbNYEuN4Zrb8maSIol
"""

print("Enter space separated int values to form the list : ")
lst=list(map(int,input().split()))
even=0
odd=0
print("You have entered : ",lst)
for i in lst:
  if i%2==0:
    even+=1
  else:
    odd+=1

print("Total even numbers : ",even)
print("Total odd numbers : ",odd)

lst=[item for item in lst if item%2!=0]
print("After removing the even items : ",lst)