# -*- coding: utf-8 -*-
"""problem-03-01111092.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cVjm6amTY_EllMbNYEuN4Zrb8maSIol
"""

print("Enter the list (space separated values) : ")
lst=list(map(int,input().split()))
print("Before update : ",lst)
lst=list(set(lst))
print("After update : ",lst)