# -*- coding: utf-8 -*-
"""problem-06-01111092.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cVjm6amTY_EllMbNYEuN4Zrb8maSIol
"""

n=int(input("Enter the number : "))
flag=True
def is_prime(n):
  for i in range(2,int(n/2)):
    if n%i==0:
      globals()['flag']=False
      break
  return globals()["flag"]

if is_prime(n):
  print(f"{n} is a prime number")
else:
  print(f"{n} is not a prime number")